# -*- coding: utf-8 -*-
"""Bi-Weekly Challenge - Franklyn Obogai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8ObjHnBvOSbgig4eHGvRx6NwEjuL86k

#Bi-Weekly Challenge
---
Write a python program that prompts for inputs from the user. The inputs should be the user's name and the age.
Print the user’s name and age
Calculate the user’s DOB using the age and print to screen
State which age group the user belongs to. [ How are the different age groups defined? – Conduent Healthy Communities Institute](https://help.healthycities.org/hc/en-us/articles/219556208-How-are-the-different-age-groups-defined-)
What was the user’s age a decade ago? (print to screen)
For the next 50 years, print what the user’s age will be after every decade (NB: The current year is 2020 :))

---
#####SAMPLE OUTPUT:

Hello John Doe, you are 3 years old<br>
Your year of birth is 2051<br>
As you are 3 years old, you are an adult<br>
In 2046 you were -7 years old<br>
In 2064 you’ll be 13y.o<br>
In 2074 you’ll be 23y.o<br>
.<br>
.<br>
In 2104 you’ll be 53y.o
"""

#Solution

from datetime import *
#From the question, current year is 2020. So the variable "today_in_2020" is intended to set a date in 2020 for use in the succeeding computation.  
current_year = 2020
today_in_2020 = str(date.today() - timedelta(days=365))

name = input("What is your name?: ")
age = int(input("How old are you?: "))
#Below is the input function to capture name and age.
def capture_detail(name, age):
  dob = datetime.strptime(today_in_2020, "%Y-%m-%d") - timedelta(days=(365*int(age))) #dob (Date of birth) is calculated by subtracting the 'age' inputed from the set date.
  yob = dob.year #yob (Year of birth) - this codes pulls the year from the above code. 

#Creates a list for ages and years
  ages = []
  years = [] 
    
  for i in range(10,60,10): 
    age_new = age + i
    ages.append(age_new)
    year_new = current_year + i
    years.append(year_new)
    
  def age_group(age):
    if age < 1:
      age_range = "an infant"
    elif age == 1 or age <= 11:
      age_range = "a child"
    elif age == 12 or age <= 17:
      age_range = "a teenager"
    elif age == 18 or age <= 64:
      age_range = "an adult"
    else:
      age_range = "an older adult"
    return age_range 
  return print(
"Hello", name, "you are", age, "years old.\n",
"Your year of birth is,", yob, "\n",
"As you are", age, "years old, you are", age_group(age),"\n",
"In", years[0], "you will be", ages[0], "years old.\n",
"In", years[1], "you will be", ages[1], "years old.\n",
"In", years[2], "you will be", ages[2], "years old.\n",
"In", years[3], "you will be", ages[3], "years old.\n",
"In", years[4], "you will be", ages[4], "years old.\n")

capture_detail(name, age)